### ISSUE TITLE
Design an error page

### ISSUE THREAD

**Issue by martinheidegger** [we-are-root/site#14]
The error page is rather crude...

**Comment by lixonic** [comment]
![weareroot](https://cloud.githubusercontent.com/assets/934220/5751862/70586848-9c90-11e4-97ed-da5427c61173.png)

**Comment by martinheidegger** [comment]
Too awesome! @lixonic I think i will improve on that but the Idea is nice

**Comment by martinheidegger** [comment]
I adopted your design in https://github.com/we-are-root/site/commit/7ec51dedc722bcfc6ea4b2a1666cd6163e14f714
