### ISSUE TITLE
Make sure people understand that "ROOT" is a button

### ISSUE THREAD

**Issue by martinheidegger** [we-are-root/site#4]
Is that possible?

**Comment by lixonic** [comment]
IMHO, there is no better way than rotating the menu text and content like http://tympanus.net/Tutorials/CSS3RotatingWords/index2.html . maybe adding next/prev works well

and we can also avoid #13 too . thoughts?

**Comment by martinheidegger** [comment]
@lixonic Thank you for the hint. It is quite suble indeed. But I don't think it will get a "button" feeling :thought_balloon: Need to give this more thought.

**Comment by lixonic** [comment]
is this broken css or intentional ? it made me to hover the cursor over it. :)

**Comment by martinheidegger** [comment]
Broken css

**Comment by martinheidegger** [comment]
@AtuyL came up with quite a good way (design is still worth improving) That I think we will go with.

http://staging.we-are-root.divshot.io/
